### ISSUE TITLE
Release mode S3 Upload Error only for Release but Debug mode proper working

### ISSUE THREAD

**Issue by Devarshi-Dhamecha** [abhimortal6/simple_s3#18]
Code:-
String result = await _simpleS3.uploadFile(
        File(fileName),
        S3Credential.s3BucketName,
        S3Credential.s3BucketPoolId,
        AWSRegions.apSouth1,
        fileName: customFileName,
        debugLog: true,
        s3FolderPath: "${S3Credential.ProductUploadImagePath}/$productId",
      );

Error :-
S3 Upload Error------------------>
E/flutter (24565): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SimpleS3Errors.UploadError
E/flutter (24565): #0      SimpleS3.uploadFile (package:simple_s3/simple_s3.dart:100)
E/flutter (24565): <asynchronous suspension>
E/flutter (24565): #1      S3UploadImage.s3Upload (package:admin/ApiController/S3Upload.dart:13)
E/flutter (24565): <asynchronous suspension>
E/flutter (24565): #2      _UpdateProductNewState.s3Function (package:admin/screens/Update_Product/Screen/updateproduct_new.dart:1089)
E/flutter (24565): <asynchronous suspension>
E/flutter (24565): #3      _UpdateProductNewState.addProductFifthClass.<anonymous closure> (package:admin/screens/Update_Product/Screen/updateproduct_new.dart:997)
E/flutter (24565): <asynchronous suspension>

**Comment by sirwes** [comment]
I also have this issue

I/flutter ( 1203): File Name: testvideo.mp4
I/flutter ( 1203):
I/flutter ( 1203): Content Type: video/mp4
I/flutter ( 1203):
I/flutter ( 1203): Status: Error
I/flutter ( 1203):
I/flutter ( 1203): S3 Upload Error------------------>
E/flutter ( 1203): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: SimpleS3Errors.UploadError
E/flutter ( 1203): #0      SimpleS3.uploadFile (package:simple_s3/simple_s3.dart:100)
E/flutter ( 1203): <asynchronous suspension>
E/flutter ( 1203): #1      _ProgressUploadWidgetState.makePutRequest (package:videos_me/progressUpload/progress_upload.dart:42)
E/flutter ( 1203): <asynchronous suspension>

**Comment by sirwes** [comment]
In the Readme, it says this

> Android Proguard settings for release mode 
> 
> // add these lines in your app/build.gradle
> 
> 		minifyEnabled true  
> 		useProguard true  
> 		proguardFiles getDefaultProguardFile('proguard-android.txt'),  
> 		        'proguard-aws-2.1.5.pro'
> 
> //EXAMPLE
> 		buildTypes {  
> 		  release {  
> 		  signingConfig signingConfigs.release  
> 		  minifyEnabled true  
> 		  useProguard true  
> 		  proguardFiles getDefaultProguardFile('proguard-android.txt'),  
> 		                'proguard-aws-2.1.5.pro'  
> 		  }  
> 		}
> Now copy contents of this file [proguard-aws-2.1.5.pro](https://github.com/abhimortal6/simple_s3/blob/master/proguard-aws-2.1.5.pro) Create a new file with name "proguard-aws-2.1.5.pro" at the same location as app/build.gradle and paste the copied contents into this file.
> 
> Your release mode APK should work now.



That worked for me

**Comment by HeyItsBablu** [comment]
When I use the use the solution from the readme, I am not able to create apk or app bundle any more. It show error.

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\Flutter\Reveja-dev\android\app\build.gradle' line: 35

* What went wrong:
A problem occurred evaluating project ':app'.
> No signature of method: build_8atkmst4anwc56rhcjo395ccq.android() is applicable for argument tyes: (build_8atkmst4anwc56rhcjo395ccq$_run_closure2) values: [build_8atkmst4anwc56rhcjo395ccq$_runclosure2@7f8e57c0]

**Comment by canisiusa** [comment]
Hi [Rosanchaudhary](https://github.com/Rosanchaudhary), replace 
useProguard true
by shrinkResources

**Comment by CodeKiteshub** [comment]
not working any resolution for me

**Comment by Rajkumar07793** [comment]
same probem


You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':simple_s3'.
> Could not resolve all files for configuration ':simple_s3:classpath'.
   > Could not find com.moowork.gradle:gradle-node-plugin:1.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/moowork/gradle/gradle-node-plugin/1.0.0/gradle-node-plugin-1.0.0.pom
       - https://jcenter.bintray.com/com/moowork/gradle/gradle-node-plugin/1.0.0/gradle-node-plugin-1.0.0.pom
     Required by:
         project :simple_s3 > com.amazonaws:aws-android-sdk-appsync-gradle-plugin:2.7.5
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':simple_s3' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':simple_s3' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
