### ISSUE TITLE
Random crash issue

### ISSUE THREAD

**Issue by Komal-Khairnar** [abhimortal6/simple_s3#6]
Hello @abhimortal6 , I am using simple_s3 plugin to upload files to Amazon s3 bucket. It is crashing the app randomly with below logs. Kindly help.

D/AndroidRuntime( 7751): Shutting down VM
W/System.err( 7751): AndroidDefaultUncaughtExceptionHandler Begin-->
W/System.err( 7751): defaultUncaughtExceptionHandler is:org.chromium.base.JavaExceptionReporter
W/System.err( 7751): FATAL EXCEPTION: main
W/System.err( 7751): java.lang.IllegalStateException: Reply already submitted
W/System.err( 7751): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
W/System.err( 7751): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
W/System.err( 7751): 	at com.abhimortal6.simple_s3.SimpleS3Plugin$Transfer.onStateChanged(SimpleS3Plugin.java:279)
W/System.err( 7751): 	at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$2.run(TransferStatusUpdater.java:206)
W/System.err( 7751): 	at android.os.Handler.handleCallback(Handler.java:751)
W/System.err( 7751): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err( 7751): 	at android.os.Looper.loop(Looper.java:154)
W/System.err( 7751): 	at android.app.ActivityThread.main(ActivityThread.java:6242)
W/System.err( 7751): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 7751): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
W/System.err( 7751): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
W/System.err( 7751): AndroidDefaultUncaughtExceptionHandler End<--

**Comment by abhimortal6** [comment]
Hi, can you share your dart code?

**Comment by Komal-Khairnar** [comment]
Below code works fine. But sometimes it crashes the app.

 String uploadedURL = await SimpleS3().uploadFile(
          file, // any file
          '$bucketName/$folderPath', 
          identity,
         AWSRegions.apSouth1,
          fileName: fileName,
        );
print('$uploadedURL');

**Comment by abhimortal6** [comment]
It doesn't seems to be a plugin issue. Check here
 https://stackoverflow.com/questions/55846479/is-there-an-solution-for-java-lang-illegalstateexception-reply-already-submitte
 
 try changing/upgrading flutter version. Also please point out the exact recreation steps so I can reproduce this.

**Comment by Komal-Khairnar** [comment]
Tried upgrading flutter, still same issue. I have multiple files that I am sending using for loop. Sometimes, after the file is successfully uploaded, app is crashing on below line with the given logs.

print('$uploadedURL');

**Comment by abhimortal6** [comment]
Yes, I had a doubt you were doing this in loop. Is it possible if you can share the full code or just the loop.

**Comment by poojabokdia** [comment]
Any updates on this issue ?

**Comment by federico-amura-kenility** [comment]
Any updates?
