### ISSUE TITLE
Uploading multiple images

### ISSUE THREAD

**Issue by liseorh** [abhimortal6/simple_s3#8]
Hello @abhimortal6.
An error occurs when uploading multiple images.
The image upload succeeds but crashes after completion.
I want to upload multiple images.
Thans.

D/Transfer(28433): ID:11 bytesCurrent: 7052 bytesTotal: 7052 100%
D/Transfer(28433): ID:10 bytesCurrent: 6312 bytesTotal: 6312 100%
D/Transfer(28433): ID:8 bytesCurrent: 35934 bytesTotal: 35934 100%
D/Transfer(28433): onStateChanged: "COMPLETED,
D/AndroidRuntime(28433): Shutting down VM
E/AndroidRuntime(28433): FATAL EXCEPTION: main
E/AndroidRuntime(28433): Process: kr.smobile.app.arooo.dev, PID: 28433
E/AndroidRuntime(28433): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(28433): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
E/AndroidRuntime(28433): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime(28433): 	at com.abhimortal6.simple_s3.SimpleS3Plugin$Transfer.onStateChanged(SimpleS3Plugin.java:279)
E/AndroidRuntime(28433): 	at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$2.run(TransferStatusUpdater.java:206)
E/AndroidRuntime(28433): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(28433): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(28433): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(28433): 	at android.app.ActivityThread.main(ActivityThread.java:7124)
E/AndroidRuntime(28433): 	at java.lang.reflect.Method.invoke(Native Method)

**Comment by vichuer** [comment]
I am having the same issue. Did you find a solution?
